// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct ContactsModel {
  var sorKey: String
  var displayName: String? = nil
  var phoneList: [PhoneInfo]? = nil
  var avatar: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContactsModel? {
    let sorKey = pigeonVar_list[0] as! String
    let displayName: String? = nilOrValue(pigeonVar_list[1])
    let phoneList: [PhoneInfo]? = nilOrValue(pigeonVar_list[2])
    let avatar: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])

    return ContactsModel(
      sorKey: sorKey,
      displayName: displayName,
      phoneList: phoneList,
      avatar: avatar
    )
  }
  func toList() -> [Any?] {
    return [
      sorKey,
      displayName,
      phoneList,
      avatar,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PhoneInfo {
  var label: String
  var number: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PhoneInfo? {
    let label = pigeonVar_list[0] as! String
    let number = pigeonVar_list[1] as! String

    return PhoneInfo(
      label: label,
      number: number
    )
  }
  func toList() -> [Any?] {
    return [
      label,
      number,
    ]
  }
}

private class FlutterContactIndexHostChannelPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ContactsModel.fromList(self.readValue() as! [Any?])
    case 130:
      return PhoneInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterContactIndexHostChannelPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ContactsModel {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PhoneInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterContactIndexHostChannelPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterContactIndexHostChannelPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterContactIndexHostChannelPigeonCodecWriter(data: data)
  }
}

class FlutterContactIndexHostChannelPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterContactIndexHostChannelPigeonCodec(readerWriter: FlutterContactIndexHostChannelPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterContactIndexHostApi {
  func getAllContacts(completion: @escaping (Result<[ContactsModel], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterContactIndexHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FlutterContactIndexHostChannelPigeonCodec.shared }
  /// Sets up an instance of `FlutterContactIndexHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterContactIndexHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getAllContactsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_contact_index.FlutterContactIndexHostApi.getAllContacts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllContactsChannel.setMessageHandler { _, reply in
        api.getAllContacts { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAllContactsChannel.setMessageHandler(nil)
    }
  }
}
