// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class ContactsModel {
  ContactsModel({
    required this.sorKey,
    this.displayName,
    this.phoneList,
    this.avatar,
  });

  String sorKey;

  String? displayName;

  List<PhoneInfo>? phoneList;

  Uint8List? avatar;

  Object encode() {
    return <Object?>[
      sorKey,
      displayName,
      phoneList,
      avatar,
    ];
  }

  static ContactsModel decode(Object result) {
    result as List<Object?>;
    return ContactsModel(
      sorKey: result[0]! as String,
      displayName: result[1] as String?,
      phoneList: (result[2] as List<Object?>?)?.cast<PhoneInfo>(),
      avatar: result[3] as Uint8List?,
    );
  }
}

class PhoneInfo {
  PhoneInfo({
    required this.label,
    required this.number,
  });

  String label;

  String number;

  Object encode() {
    return <Object?>[
      label,
      number,
    ];
  }

  static PhoneInfo decode(Object result) {
    result as List<Object?>;
    return PhoneInfo(
      label: result[0]! as String,
      number: result[1]! as String,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ContactsModel) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is PhoneInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return ContactsModel.decode(readValue(buffer)!);
      case 130: 
        return PhoneInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FlutterContactIndexHostApi {
  /// Constructor for [FlutterContactIndexHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterContactIndexHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<ContactsModel>> getAllContacts() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_contact_index.FlutterContactIndexHostApi.getAllContacts$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ContactsModel>();
    }
  }
}
