// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.hzm.flutter_contact_index

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class ContactsModel (
  val sorKey: String,
  val displayName: String? = null,
  val phoneList: List<PhoneInfo>? = null,
  val avatar: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContactsModel {
      val sorKey = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String?
      val phoneList = pigeonVar_list[2] as List<PhoneInfo>?
      val avatar = pigeonVar_list[3] as ByteArray?
      return ContactsModel(sorKey, displayName, phoneList, avatar)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sorKey,
      displayName,
      phoneList,
      avatar,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PhoneInfo (
  val label: String,
  val number: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PhoneInfo {
      val label = pigeonVar_list[0] as String
      val number = pigeonVar_list[1] as String
      return PhoneInfo(label, number)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      label,
      number,
    )
  }
}
private open class FlutterContactIndexHostChannelPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContactsModel.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PhoneInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ContactsModel -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PhoneInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterContactIndexHostApi {
  fun getAllContacts(callback: (Result<List<ContactsModel>>) -> Unit)

  companion object {
    /** The codec used by FlutterContactIndexHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterContactIndexHostChannelPigeonCodec()
    }
    /** Sets up an instance of `FlutterContactIndexHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterContactIndexHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_contact_index.FlutterContactIndexHostApi.getAllContacts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAllContacts{ result: Result<List<ContactsModel>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
